# Generated by Django 5.0.3 on 2024-09-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('next_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_options', to='story.sectionmodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='story.sectionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='story.storymodel'),
        ),
    ]
